---
latitude: 40.75243
longitude: -73.98946
map_zoom: 12
name: Moxy NYC Times Square
email: sgontu@traveltripper.com
phone_number: 001-111-1111
address:
  street1: 485 7th Avenue
  street2: ''
  state: New York
  city: New York
  country: United States
  zip_code: '10018'
_hotel_id: MOX821
_portal_id: required-but-empty
_root_path: https://rt3api-prd.ttaws.com
